Udfm 69 마트업
gnar-rengar/frontend pull request #54
Opened 2022-07-14 10:44 UTC by JhsK

## 작업 사항
- 홈 페이지 마크업
- 디자인 시스템 surface 색상 추가 및 chip 패딩 수정
- 추천 카드 컴포넌트 추가
- 카드 컴포넌트 플레이스타일 개수 로직 수정
## 기타
![image](https://user-images.githubusercontent.com/69228184/178965020-a89e9455-2e0d-417b-a208-19843cec6b1d.png)

2022-07-14 11:45 UTC, jaesoekjjang requested changes

2022-07-14 11:45 UTC, jaesoekjjang commented on src/components/common/typography/Typography.style.tsx
> +      & > a {
이 부분은 지난번에 리뷰때 의견 남겨드렸는데  답글이 없으셨네용. 개인적으로 수정 됐으면 하는 부분입니다.

2022-07-14 13:00 UTC, JhsK commented on src/components/common/typography/Typography.style.tsx
> +      & > a {
지난 리뷰때 못 봤던거 같은데 놓쳤나보네요

2022-07-15 03:43 UTC, jaesoekjjang approved these changes
수고하셨습니다!

2022-07-15 04:31 UTC, merged