Udfm 65 온보딩 api 백엔드 테스트
gnar-rengar/frontend pull request #61
Opened 2022-07-18 12:49 UTC by JhsK

## 작업 사항
- 백엔드 API 테스트
- 480px 최대 너비 디자인 적용
- 기존 유저 정보 불러오기 API 작성 및 온보딩 연동 작업
## 기타

2022-07-18 12:57 UTC, JhsK commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
배열 인덱스 0,1,2,3 등으로 작성하면 에러가 나서 추가하였습니다!

2022-07-19 02:07 UTC, jaesoekjjang requested changes

2022-07-19 02:18 UTC, JhsK commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
`Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'PlayStyleType'` 타입에러라서 `string[] | PlayStyleType`이랑은 관계 없는거 아닌가요?!

2022-07-19 02:41 UTC, JhsK commented on src/components/common/chip/CheckBoxChip.tsx
> +      <Input type="checkbox" value={htmlFor} id={htmlFor} {...register} />
아 작업하면서 잠깐 지웠는데 빼먹었네요 ㅠ 다시 추가했습니다!

2022-07-19 04:40 UTC, JhsK commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
제네릭으로 에러 수정했습니다!

2022-07-19 04:42 UTC, JhsK commented on src/components/common/chip/RadioChip.tsx
> +  const playStyleDetail = watch(`playStyle.${other.name}`);
말씀해주신 `playStyle`같이 온보딩에만 한정적으로 사용할 수 있었던 부분들은 제거 및 공용으로 사용할 수 있도록 수정하였습니다. 다만 RadioChip, CheckBoxChip 과 같이 폼에 관련있는 컴포넌트들은 결국 `react-hook-form`의 의존성은 어쩔 수 없을 것 같습니다..

2022-07-19 05:34 UTC, jaesoekjjang commented on src/components/common/chip/RadioChip.tsx
> +  const playStyleDetail = watch(`playStyle.${other.name}`);
간단히 작성해봤는데 대충 이런식으로 해주면 `register`를 제외한 의존성을 모두 걷어낼 수 있을 것 같습니다.

```
function RadioChip(props: RadioChipProps) {
  const { htmlFor, value, width = 'fit-content', register, name, ...other } = props;

  const [isChecked, setIsChecked] = useState(false);

  useEffect(() => {
    if ((document.querySelector(`#${value}`) as HTMLInputElement).checked === true) {
      setIsChecked(true);
    } else {
      setIsChecked(false);
    }
  }, [(document.querySelector(`#${value}`) as HTMLInputElement).checked]);

  return (
    <SelectLabel width={width} htmlFor={htmlFor}>
      <Input
        type="radio"
        value={value}
        defaultChecked={false}
        id={value}
        name={name}
        {...register}
      />
      <Chip chosen={isChecked} {...other} />
    </SelectLabel>
  );
}
```

2022-07-19 05:39 UTC, jaesoekjjang commented on src/components/common/chip/RadioChip.tsx
> +  const playStyleDetail = watch(`playStyle.${other.name}`);
![image](https://user-images.githubusercontent.com/78065948/179673412-36ea32b9-8f6c-4c12-b163-3d1c79f762ac.png)

2022-07-19 06:47 UTC, jaesoekjjang approved these changes
고생하셨습니다!

2022-07-19 06:48 UTC, merged