Udfm 79 성향검사 알고리즘 작업
gnar-rengar/frontend pull request #67
Opened 2022-07-22 03:45 UTC by JhsK

## 작업 사항
- 성향 검사 결과 온보딩 페이지 전달 및 defaultValues 설정
## 기타

2022-07-22 03:46 UTC, JhsK commented on src/components/common/chip/Chip.style.tsx
> +  size?: 'sm' | 'lg' | 'body1';
성향 검사 결과에 나와있는 chip에 타이포그래피가 body1인데 사이즈 변수값을 어떻게 주는게 좋을까요?

2022-07-22 04:42 UTC, jaesoekjjang commented on src/components/tendencyTest/index.tsx
>    }, [testNumber]);
여기서 useMemo를 사용해야할 이유가 있을까요??

2022-07-22 04:42 UTC, jaesoekjjang commented on src/components/common/chip/Chip.style.tsx
> +  size?: 'sm' | 'lg' | 'body1';
글쎄요 xl...?

아님 body4로 뒀을 때가 더 예뻐보이는데.. 예지님한테 body4는 어떠신지 여쭤보는건..?

2022-07-22 04:42 UTC, jaesoekjjang commented on src/components/common/chip/Chip.style.tsx
> +    if (size === 'sm' || size === 'body1') return 'padding: 4px 8px;';
![image](https://user-images.githubusercontent.com/78065948/180363133-6b3b3424-7554-4dc8-8722-ea7fa3ed5638.png)

패딩이 텍스트 길이마다 다릅니당. 칩 width가 왜 100%로 돼있죵

2022-07-22 04:42 UTC, jaesoekjjang commented on src/components/common/chip/Chip.style.tsx
> +    if (size === 'sm' || size === 'body1') return 'padding: 4px 8px;';
width를 없애거나 auto로 바꾸고 ChipContainer를 없애는게 좋을 듯 합니당.

![image](https://user-images.githubusercontent.com/78065948/180363769-82fb1b11-9b50-48dd-b8e2-a28f0856d927.png)

2022-07-22 04:47 UTC, jaesoekjjang commented on src/components/common/chip/Chip.style.tsx
> +    if (size === 'sm' || size === 'body1') return 'padding: 4px 8px;';
onBoarding에서 칩 너비가 고정 돼야해서 100%로 해두신거였죵??

width를 선택적으로 받아서 undefined인 경우 auto로 하면 될 것 같습니다.

2022-07-22 06:11 UTC, JhsK commented on src/components/tendencyTest/index.tsx
>    }, [testNumber]);
`testAnswer`도 `testNumber`와 동일하게 자식 컴포넌트의 props로 넘겨주어 사용하게 되는데 `pageRenderMemo`함수에서는 `testNumber` 값에서 return 값이 달라지기 때문에 굳이 `testAnswer` 변화로 리렌더링 될 때 `pageRenderMemo`가 영향을 계속 받을 필요가 없다고 생해서 `useMemo`를 사용했습니다.

흠.. 이렇게 텍스트로 설명하니 제대로 이해가 되셨을지 모르겠네요 ㅠㅠ 이해가 어려우시면 디코로 제가 설명드리겠습니다!

2022-07-23 01:29 UTC, jaesoekjjang commented
![image](https://user-images.githubusercontent.com/78065948/180585167-98bdb153-96ec-4f63-9edc-69b61f910c66.png)
![image](https://user-images.githubusercontent.com/78065948/180585196-3eaa1295-e7df-42bd-90ee-edbd32600819.png)

칩 크기 맞춰주세요~ 패딩이 항상 같아야 합니다

2022-07-23 01:31 UTC, jaesoekjjang requested changes

2022-07-23 02:56 UTC, jaesoekjjang approved these changes
수고하셨습니다~

2022-07-23 04:53 UTC, merged