Udfm 82 모아보기
gnar-rengar/frontend pull request #80
Opened 2022-07-31 07:57 UTC by JhsK

## 작업 사항
- 커스텀 추천 페이지 마크업 및 api 작업
- 뉴 소환사 리스트 페이지 마크업 및 api 작업
- 개인정보보호처리방침 페이지 작성
- 
![image](https://user-images.githubusercontent.com/69228184/182015863-720cc885-4a37-48d6-9103-5d5721c87d9a.png)
![image](https://user-images.githubusercontent.com/69228184/182015883-15c20852-5335-4ede-91f3-6bcc02f185ec.png)

## 기타
- 이용약관 페이지는 아직 진행 중이며 성향검사 공유하기 기능 브랜치에서 같이 작업해서 마무리하겠습니다

2022-07-31 07:59 UTC, JhsK commented on src/components/home/index.tsx
> +  const newList = () => pages.map((page) => page.data.newList.filter((list, index) => index <= 2));
`select` 로 해보려고 했는데 계속 타입오류가 나서 select는 추후 리팩토링으로 미루고 우선은 홈 페이지에서 직업 filter로 가공을 했습니다. 더 좋은 방법이 있을까요?

2022-07-31 08:01 UTC, JhsK commented on src/components/home/index.tsx
> +  const recommendProps = () => {
로그인 하지 않은 사용자가 홈 페이지에 접근했을 때 맞춤 소환사 리스트가 블러 처리하였지만 어느정도 데이터가 존재해야 하기 때문에 이러한 경우에는 뉴 소환사 리스트 데이터로 대신 보여주는 방식으로 표현했습니다.

2022-07-31 13:55 UTC, jaesoekjjang commented
![image](https://user-images.githubusercontent.com/78065948/182029703-e23b44b2-0a90-4a01-be86-cbd92f69b3aa.png)

좁은 화면에서 swiper가 겹쳐보이네요 의도하신 형태는 아니시죠??

2022-07-31 14:12 UTC, jaesoekjjang commented
arrow 아이콘들 가져오실 때 frame을 제외하고 vector만 가져오신것 같아요. 그래서 같은 16x16으로 설정해도 디자인보다 아이콘이 더 커집니다

2022-07-31 14:58 UTC, jaesoekjjang requested changes

2022-07-31 14:58 UTC, jaesoekjjang commented on src/hooks/queryKeys.ts
> +  customList: ['customList'] as const,
얘네들은 string key로 두어도 될것 같은데 배열로 하신 이유가 따로 있으신지 궁금하네요!

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/home/style.ts
> +export const BlurContainer = styled.div`
MoreContainer의 gap이 4px이 되어야할것 같습니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/types/api.type.ts
> +export interface CardProps {
컴포넌트 props 타입은 컴포넌트 내에 작성하는게 좋을듯 합니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/pages/recommend/fit.tsx
> +import React from 'react';
recommend fit, new 페이지 모두 아래같은 에러가 발생합니다
![image](https://user-images.githubusercontent.com/78065948/182030839-b6442182-5207-4178-81a3-551409decef8.png)

2022-07-31 14:58 UTC, jaesoekjjang commented on src/pages/recommend/fit.tsx
> +import React from 'react';
null 체크 또는 lazy load를 해야할 것 같습니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/recommend/Filter.tsx
> +              onClick={() => setOpen((prev) => !prev)}
화살표 뿐만 아니라 필터 어느곳을 눌러도 필터가 열리는 편이 좋을 것 같습니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/pages/recommend/fit.tsx
> +import React from 'react';
헤더에서 이들 페이지로 이동할 수 있도록 링크 달아주세요!

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/home/RecommendSwiper.tsx
> +              <LargeCard {...list} key={list._id} />
recommend 페이지의 카드들과 마찬가지로 프로필로 곧장 이동할 수 있는 링크가 필요할 것 같습니다~

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/recommend/Fit.tsx
> +                  <LargeCard {...list} key={list._id} />
`Link`에 `key`가 있으므로 `LargeCard`에서는 빼도 될것 같습니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/home/index.tsx
> +        {!userData && !userData?.lolNickname && <Blur />}
요건 결국 `lolNickname`이 없을 때 만을 검사했을 때와 같지 않나요??

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/home/index.tsx
> +  const newList = () => pages.map((page) => page.data.newList.filter((list, index) => index <= 2));
임시로 둔거긴 하지만 `newList()`는 함수가 아니라 그 값이 되는게 더 좋을 것 같습니다. 

동일한 값을 얻기 위해 `recommentProps`에서, Line 75에서, `newList()`를 총 두 번 호출하고 있습니다

2022-07-31 14:58 UTC, jaesoekjjang commented on src/components/home/index.tsx
> +  const newList = () => pages.map((page) => page.data.newList.filter((list, index) => index <= 2));
네 굳이 `select`를 사용하지 않고 받아온 값 중에 3개만 잘라서 보여주는 것도 충분히 좋은 방법이라고 생각합니다.

`filter` 보다는 `slice`를 사용하는게 더 좋을 것 같아요

2022-08-01 01:18 UTC, JhsK commented on src/components/common/index.ts
> +// eslint-disable-next-line prettier/prettier
저장을 누르면 프리티어에서 한 줄 줄바꿈을 해서 린트 에러가 나서 추가해뒀습니다 ㅜ

2022-08-01 04:54 UTC, JhsK commented on src/components/home/index.tsx
> +  const newList = () => pages.map((page) => page.data.newList.filter((list, index) => index <= 2));
앗 그러네요 수정했습니다!

2022-08-01 05:20 UTC, JhsK commented on src/components/home/index.tsx
> +        {!userData && !userData?.lolNickname && <Blur />}
역기 갓재석..

2022-08-01 05:27 UTC, JhsK commented on src/hooks/queryKeys.ts
> +  customList: ['customList'] as const,
string key로 설정해도 리액트 쿼리에서는 내부적으로 배열로 다시 변환해서 처리하는 것으로 알고 있어서 가급적이면 배열로 사용하려고 하고 있습니당 

배달의민족 리액트 쿼리 세미나에서도 배열로 권장을 하고 있구요

2022-08-01 06:03 UTC, JhsK commented on src/pages/recommend/fit.tsx
> +import React from 'react';
감사합니다!

2022-08-01 06:46 UTC, JhsK commented
네 그래서 swiper는 미디어 쿼리로 화면 크기별 마진을 설정하려고 생각했었습니다 ㅜ

2022-08-01 07:03 UTC, jaesoekjjang approved these changes
수고하셧습니다~ 필터 초기화만 추가하고 머지 해주세요!

2022-08-01 07:03 UTC, jaesoekjjang commented on src/components/recommend/New.tsx
> +import React, { useEffect, useState } from 'react';
필터를 모두 해제하고 적용했을 때 다시 전체 최신 소환사를 받아올 수 있도록 해야할 것 같습니다~

2022-08-01 09:04 UTC, JhsK commented on src/components/recommend/New.tsx
> +import React, { useEffect, useState } from 'react';
아 그러네요 수정했습니다!

2022-08-01 09:07 UTC, merged